run:
  deadline: 3m
  issues-exit-code: 1
  tests: false

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  errcheck:
    check-blank: true
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - encoding/json.Marshal

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - goimports
    - gosimple
    - unused
    - staticcheck
    - dupl
