run:
  deadline: 3m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - goimports
    - gosimple
    - unused
    - staticcheck
    # - dupl

#issues:
#  exclude-use-default: false
#  exclude:
#    - G104
#    - exported func * returns unexported type *, which can be annoying to use
#    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
#    - should have a package comment, unless it's in another file for this package
#    - don't use an underscore in package name
#    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
#    - should check returned error before deferring
#    - (struct field|func|const) .*Dns.* should be .*DNS.*
